# This file is a placeholder for your Linera project.
# It assumes your project is a standard Rust workspace.
{
  pkgs,
  crane,
  rust-toolchain,
  ...
}: let
  # The cargo.nix file is generated by `crane`, which caches dependencies.
  # This provides a faster build process.
  craneLib = crane.lib.${pkgs.system};
  src = craneLib.cleanCargoSource ./.;
  cargoDeps = craneLib.buildDepsOnly {
    inherit src;
    nativeBuildInputs = [pkgs.pkg-config];
    buildInputs = [
      pkgs.openssl
      pkgs.libiconv
    ];
  };
in
  pkgs.callPackage rust-toolchain {
    buildInputs = [pkgs.pkg-config];
    build = pkgs.stdenv.mkDerivation {
      pname = "microchess";
      version = "0.1.0";
      inherit src;

      # Link the cached dependencies from the previous step.
      # This avoids rebuilding them every time.
      nativeBuildInputs = [
        pkgs.pkg-config
      ];
      buildInputs = [
        pkgs.openssl
        pkgs.libiconv
      ];

      # Use `crane` to build the final project.
      # Replace `buildPhase` and `installPhase` with the correct build commands for your project.
      buildPhase = ''
        runHook preBuild
        cargo build --release
        runHook postBuild
      '';

      installPhase = ''
        runHook preInstall
        mkdir -p $out/bin
        cp target/release/your_executable_name $out/bin/
        runHook postInstall
      '';

      # Inherit the dependencies from `cargoDeps`.
      # This ensures your build has access to all required libraries.
      # Note: If your project is a workspace, you may need to adjust this.
      inherit cargoDeps;

      # This is a workaround for some common build issues with Rust projects.
      # It sets the RUST_SRC_PATH so that rust-analyzer can find standard library source code.
      RUST_SRC_PATH = "${rust-toolchain}/lib/rustlib/src/rust/library";
      LIBCLANG_PATH = "${pkgs.llvmPackages.libclang}/lib";
    };
  }
