name: chess contract test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Protocol Buffers Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Add WebAssembly target
      run: rustup target add wasm32-unknown-unknown   

    - name: Build chess project
      working-directory: ./chess
      run: cargo build --release --target wasm32-unknown-unknown
      
    - name: Run chess tests
      working-directory: ./chess
      run: cargo test --verbose
      
    - name: Check formatting
      working-directory: ./chess
      run: |
        rustup component add rustfmt
        cargo fmt -- --check       

    - name: Run clippy
      working-directory: ./chess
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings
