name: MicroChess Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: MicroChess
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain and components
        run: |
          rustup target add wasm32-unknown-unknown
          rustup toolchain install nightly --allow-downgrade -c rustfmt
          rustup component add rustfmt
          rustup component add rustfmt --toolchain nightly

      - name: Install Linera dependencies
        run: |
          git clone https://github.com/linera-io/linera-protocol.git ../linera-protocol
          cd ../linera-protocol
          git checkout -t origin/testnet_archimedes
          cargo install --locked --path linera-storage-service
          cargo install --locked --path linera-service --features storage-service

      - name: Run MicroChess tests
        run: |
          cd chess
          cargo test --verbose

