name: chess_lib

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Protocol Buffers Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.86.0
          profile: minimal
          override: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Check formatting
        working-directory: ./chess_lib
        run: |
          rustup component add rustfmt
          cargo fmt -- --check

      - name: Run clippy
        working-directory: ./chess_lib
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings

      - name: Run unit tests
        working-directory: ./chess_lib
        run: |
          cargo test --verbose

      - name: Run perft benchmark tests
        working-directory: ./chess_lib
        run: |
          cargo test --bench perft

      - name: Build for WebAssembly
        working-directory: ./chess_lib
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Run chess smart contract tests
        working-directory: ./chess
        run: cargo test --verbose
