name: MicroChess Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: MicroChess
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - run: rustup target add wasm32-unknown-unknown
      - run: rustup toolchain install nightly --allow-downgrade -c rustfmt
      - run: rustup component add rustfmt
      - run: rustup component add rustfmt --toolchain nightly
      - run: git clone https://github.com/linera-io/linera-protocol.git ../linera-protocol
      - run: cd ../linera-protocol; git checkout -t origin/testnet_archimedes
      - run: cargo install --locked --path linera-storage-service
      - run: cargo install --locked --path linera-service --features storage-service
      - run: cargo fmt --all -- --check
